### ISSUE TITLE
Not able to allocate  rooms please help!

### ISSUE THREAD

**Issue by sameerimamillapalli** [Bharat-Reddy/Hostel-Management-System#11]
Application is received but the room allocation becomes unsuccessful

**Comment by a1d9** [comment]
plz share your admin login detail

**Comment by bhatt098** [comment]
> Application is received but the room allocation becomes unsuccessful

bro your Hostel-Manager/Admin Login is working ??

**Comment by suraj2439** [comment]
> plz share your admin login detail
I faced same issue, but I solved it temporarily by doing below procedure. 
make entry in your admin/manager table with appropriate password.
but using this password you cannot sign in to account because it compares hash value of your entered password and password value in table
for solving this issue, you can change code in appropriate login php file, instead of calling function password_check() use direct comparison $password == $row["Pwd"] ,
after doing this it allows access.
